### ISSUE TITLE
Remove this unused blog from being the Operation Code 'Organization' GitHub Page

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/blog.operationcode.org#3]
https://help.github.com/articles/user-organization-and-project-pages/
https://help.github.com/articles/custom-domain-redirects-for-github-pages-sites/

Right now, the 'operationcode.github.io' repo is the Organization Page for GitHub pages.  You can only have one Organization Page (and many Project Pages).  This 'operationcode.github.io' repo houses the old Middleman blog that isn’t in use - and the CNAME file here redirects to the custom domain ‘blog.operationcode.org’.  The current blog being used is the Jekyll blog in the 'operationcode' repo in the /blog directory, and it's deployed at 'www.operationcode.org/blog'

Any custom domain for this unused Organization Page will apply the same default domain redirect to all Project Pages on the account (such as the tap-deck repo).  It doesn’t make sense to have to use blog.operationcode.org/tap-deck to access the tap deck page.  operationcode.github.io/tap-deck or operationcode.org/tap-deck (if we want to use a custom redirect) would make more sense.

I propose we either
-  delete this repo housing the unused Middleman blog as our one ‘Organization Page’
- keep the repo, but remove all the unused blog stuff, and just change the CNAME custom domain redirect to “www.operationcode.org".  If there is anything that we would want to host on the 'Organizational Page' for GitHub pages, we could eventually add it here.

:eyes: @davidmolina

**Comment by davidmolina** [comment]
Sounds good.

Delete, we can always add a GH page layer as the need arises.

**Comment by jjhampton** [comment]
I'm going to just rename this repo instead of deleting - I'd rather not outright remove work that people put in earlier.  We might want to revisit Middleman or Casper in the future.  

This will remove this branch's status as the Organizational Page for GitHub Pages.  And stop current Project Pages from redirecting to the blog.operationcode.org custom subdomain listed in the CNAME.

**Comment by jjhampton** [comment]
Renamed the repo and deleted the CNAME that had 'blog.operationcode.org' listed. However, "http://operationcode.github.io/tap-deck" is still redirecting to "http://blog.operationcode.org/tap-deck/".

Maybe it takes time before the GitHub DNS redirect stops taking effect.  I opened a help ticket w/ GitHub tech support.

**Comment by jjhampton** [comment]
http://operationcode.github.io/tap-deck is working now.  Might have been an issue with me having to clear my browser cache.  Also flushed my machine and browser's DNS cache.  Or maybe GitHub tech support is just-that-good. 

Closing.
